<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net9.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable></PropertyGroup><ItemGroup><Compile Include="../../windows/DirectDownloads.cs" Link="DirectDownloads.cs"/><Compile Include="../../windows/Transfers.cs" Link="Transfers.cs"/><Compile Include="../../windows/Conversations.cs" Link="Conversations.cs"/><Compile Include="../../windows/PeerEngine.cs" Link="PeerEngine.cs" /><Compile Include="../../windows/SecureIdentity.cs" Link="SecureIdentity.cs" /><Compile Include="../../windows/SecureChannel.cs" Link="SecureChannel.cs" /><Compile Include="../../windows/NetworkTimeoutStream.cs" Link="NetworkTimeoutStream.cs" /></ItemGroup><ItemGroup><PackageReference Include="BouncyCastle.Cryptography" Version="2.7.0" /></ItemGroup></Project>
