<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>2.2.42</Version>
    <AssemblyName>LanMessenger</AssemblyName>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <ApplicationIcon>lan-messenger.ico</ApplicationIcon>
  </PropertyGroup>
<ItemGroup><PackageReference Include="BouncyCastle.Cryptography" Version="2.7.0" /><PackageReference Include="SIPSorcery" Version="10.0.17" /></ItemGroup></Project>
