package net.lanmsg.chat;

import android.app.*;
import android.content.*;
import android.os.*;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.view.View;
import android.widget.*;
import android.text.InputFilter;
import java.util.*;
import java.net.*;
import java.io.*;
import android.net.Uri;
import android.provider.OpenableColumns;
import android.provider.MediaStore;
import android.database.Cursor;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.graphics.Rect;
import android.view.ViewTreeObserver;

public class MainActivity extends Activity {
  final Handler ui=new Handler(Looper.getMainLooper());
  final int ink=Color.rgb(17,27,33),accent=Color.rgb(37,211,102),headerDark=Color.rgb(7,94,84),chatBg=Color.rgb(236,229,221),bubbleMine=Color.rgb(220,248,198),seenBlue=Color.rgb(83,169,239),panelBg=Color.rgb(240,242,245);
  final int[] namePalette={Color.rgb(233,30,99),Color.rgb(156,39,176),Color.rgb(63,81,181),Color.rgb(230,126,0),Color.rgb(0,137,123),Color.rgb(121,85,72),Color.rgb(216,67,21)};
  int nameColor(String id){int h=0;for(int i=0;i<id.length();i++)h=h*31+id.charAt(i);return namePalette[Math.abs(h)%namePalette.length];}
  LinearLayout root,body,feed,attachmentDraft; TextView status,heading; ScrollView scroll; EditText composer; Button send,verifyButton;
  String selected=null,lastSignature="",attachmentTarget=null,pendingOpen=null,pendingAttachmentName="",pendingAttachmentTarget=null; byte[] pendingAttachment; Uri cameraUri; File cameraFile; PeerEngine.Message exportMessage; boolean active; final Map<String,String> drafts=new HashMap<>();
  ViewTreeObserver.OnGlobalLayoutListener keyboardListener;
  final Runnable tick=new Runnable(){public void run(){render();if(active)ui.postDelayed(this,1000);}};
  int dp(int x){return (int)(x*getResources().getDisplayMetrics().density);}
  TextView label(String text,int size){TextView t=new TextView(this);t.setText(text);t.setTextColor(ink);t.setTextSize(size);t.setPadding(0,dp(6),0,dp(6));return t;}
  LinearLayout column(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}
  Button button(String text){Button b=new Button(this);b.setText(text);b.setAllCaps(false);b.setTextSize(14);b.setTextColor(accent);return b;}
  GradientDrawable circleBg(int c,int diameterDp){GradientDrawable d=new GradientDrawable();d.setColor(c);d.setCornerRadius(dp(diameterDp)/2f);return d;}
  TextView circle(String letter,int color,int diameterDp,int textSize){TextView t=new TextView(this);t.setText(letter);t.setTextColor(Color.WHITE);t.setTypeface(null,Typeface.BOLD);t.setTextSize(textSize);t.setGravity(android.view.Gravity.CENTER);t.setBackground(circleBg(color,diameterDp));return t;}
  EditText input(String hint,int max){EditText e=new EditText(this);e.setHint(hint);e.setTextSize(17);e.setSingleLine(true);e.setFilters(new InputFilter[]{new InputFilter.LengthFilter(max)});return e;}
  GradientDrawable bg(int c){GradientDrawable d=new GradientDrawable();d.setColor(c);d.setCornerRadius(dp(12));return d;}
  @Override public void onCreate(Bundle state){super.onCreate(state);getWindow().setStatusBarColor(headerDark);getWindow().setNavigationBarColor(Color.WHITE);pendingOpen=getIntent().getStringExtra("conversation");showPeople();startConnection();if(Build.VERSION.SDK_INT>=33&&checkSelfPermission("android.permission.POST_NOTIFICATIONS")!=android.content.pm.PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{"android.permission.POST_NOTIFICATIONS"},1);}
  void startConnection(){try{startForegroundService(new Intent(this,MessengerService.class));}catch(Exception e){MessengerService.problem="Could not start. Open the app and try again.";}}
  void frame(){if(root!=null)releaseImages(root);if(keyboardListener!=null){getWindow().getDecorView().getViewTreeObserver().removeOnGlobalLayoutListener(keyboardListener);keyboardListener=null;}root=column();root.setLayoutDirection(View.LAYOUT_DIRECTION_LTR);root.setBackgroundColor(panelBg);setContentView(root);
    LinearLayout headerBar=new LinearLayout(this);headerBar.setOrientation(LinearLayout.HORIZONTAL);headerBar.setGravity(android.view.Gravity.CENTER_VERTICAL);headerBar.setBackgroundColor(headerDark);headerBar.setPadding(dp(18),dp(14),dp(18),dp(14));
    TextView title=label("LAN Messenger",20);title.setTypeface(null,Typeface.BOLD);title.setTextColor(Color.WHITE);title.setPadding(0,0,0,0);headerBar.addView(title,new LinearLayout.LayoutParams(0,-2,1));root.addView(headerBar);
    LinearLayout content=column();content.setPadding(dp(18),dp(10),dp(18),dp(8));root.addView(content,new LinearLayout.LayoutParams(-1,0,1));root=content;
    status=label("Finding people on your network…",14);root.addView(status);}
  void saveDraft(){if(selected!=null&&composer!=null)drafts.put(selected,composer.getText().toString());}
  void showPeople(){saveDraft();clearPendingAttachment();selected=null;composer=null;lastSignature="";frame();
    LinearLayout tools=new LinearLayout(this);tools.setGravity(android.view.Gravity.CENTER_VERTICAL);
    FrameLayout avatarWrap=new FrameLayout(this);LinearLayout.LayoutParams avatarWrapParams=new LinearLayout.LayoutParams(dp(40),dp(40));avatarWrapParams.setMargins(0,0,dp(8),0);tools.addView(avatarWrap,avatarWrapParams);
    ImageView avatarView=new ImageView(this);avatarView.setLayoutParams(new FrameLayout.LayoutParams(-1,-1));avatarView.setScaleType(ImageView.ScaleType.CENTER_CROP);avatarView.setClipToOutline(true);
    PeerEngine ownEngine=MessengerService.engine;byte[] ownAvatar=ownEngine==null?null:ownEngine.avatar();
    Bitmap ownBitmap=ownAvatar==null?null:inlineBitmap(ownAvatar);
    if(ownBitmap!=null){avatarView.setImageBitmap(ownBitmap);avatarWrap.addView(avatarView);}
    else{avatarWrap.setBackground(circleBg(accent,40));String initial=ownEngine!=null&&!ownEngine.name.isEmpty()?ownEngine.name.substring(0,1).toUpperCase(Locale.ROOT):"?";TextView t=new TextView(this);t.setText(initial);t.setTextColor(Color.WHITE);t.setTypeface(null,Typeface.BOLD);t.setGravity(android.view.Gravity.CENTER);avatarWrap.addView(t,new FrameLayout.LayoutParams(-1,-1));}
    avatarWrap.setOnClickListener(v->changeAvatar());
    Button profile=button("Profile"),refresh=button("Refresh"),add=button("Add by IP"),about=button("About");tools.addView(profile);tools.addView(refresh);tools.addView(add);Button group=button("New group");tools.addView(group);tools.addView(about);group.setOnClickListener(v->createGroup());about.setOnClickListener(v->showAbout());HorizontalScrollView toolScroll=new HorizontalScrollView(this);toolScroll.setHorizontalScrollBarEnabled(false);toolScroll.addView(tools);root.addView(toolScroll);
    profile.setOnClickListener(v->profile());refresh.setOnClickListener(v->{PeerEngine e=MessengerService.engine;if(e==null)startConnection();else new Thread(()->{try{e.announce();}catch(Exception ignored){}}).start();lastSignature="";render();});add.setOnClickListener(v->addAddress());
    root.addView(label("Conversations",20));scroll=new ScrollView(this);body=column();scroll.addView(body);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));root.addView(label("Saved contacts stay here when offline.\nOnly devices using LAN Messenger appear.",14));render();
  }
  void showChat(String id){saveDraft();if(pendingAttachmentTarget!=null&&!pendingAttachmentTarget.equals(id))clearPendingAttachment();selected=id;lastSignature="";frame();Button back=button("‹ People");LinearLayout actions=new LinearLayout(this);actions.addView(back);Button verify=button("Verify device");verifyButton=verify;actions.addView(verify);verify.setOnClickListener(v->verifyDevice());Button more=button("More");actions.addView(more);more.setOnClickListener(v->chatMenu(more));root.addView(actions);back.setOnClickListener(v->showPeople());heading=label("",20);root.addView(heading);
    PeerEngine groupCheck=MessengerService.engine;boolean isGroup=false;if(groupCheck!=null)for(PeerEngine.Group g:groupCheck.groups())if(g.id.equals(id))isGroup=true;
    final TextView[] noticeHolder={null};if(isGroup){noticeHolder[0]=label("Group messages and their attachments are automatically deleted after 7 days of being sent.",12);noticeHolder[0].setTextColor(Color.rgb(112,128,144));root.addView(noticeHolder[0]);}
    scroll=new ScrollView(this);scroll.setFillViewport(true);scroll.setBackgroundColor(chatBg);feed=column();feed.setPadding(dp(6),dp(6),dp(6),dp(6));scroll.addView(feed);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
    attachmentDraft=column();root.addView(attachmentDraft);composer=input("Write a message or caption…",2000);composer.setSingleLine(false);composer.setMaxLines(4);composer.setText(drafts.containsKey(id)?drafts.get(id):"");root.addView(composer);LinearLayout composeActions=new LinearLayout(this);Button camera=button("Camera"),photo=button("Photo"),file=button("File");composeActions.addView(camera);composeActions.addView(photo);composeActions.addView(file);camera.setOnClickListener(v->capturePhoto());photo.setOnClickListener(v->pickFile(true));file.setOnClickListener(v->pickFile(false));send=button("Send");send.setTextColor(Color.WHITE);send.setBackgroundTintList(android.content.res.ColorStateList.valueOf(accent));composeActions.addView(send,new LinearLayout.LayoutParams(0,dp(48),1));root.addView(composeActions);
    send.setOnClickListener(v->{PeerEngine e=MessengerService.engine;if(e==null){Toast.makeText(this,"Go online to save a new message.",Toast.LENGTH_SHORT).show();return;}if(pendingAttachment==null&&composer.getText().toString().trim().isEmpty())return;try{if(pendingAttachment!=null)e.queueFile(selected,composer.getText().toString(),pendingAttachmentName,pendingAttachment);else e.queue(selected,composer.getText().toString());composer.setText("");drafts.remove(selected);clearPendingAttachment();lastSignature="";render();}catch(Exception error){Toast.makeText(this,error.getMessage(),Toast.LENGTH_LONG).show();}});renderPendingAttachment();render();
    // Collapse the action row to just the back arrow and scroll to the latest message while the keyboard covers the screen, like a typical chat app.
    View decor=getWindow().getDecorView();final boolean[] keyboardWasVisible={false};
    keyboardListener=()->{
      Rect visible=new Rect();decor.getWindowVisibleDisplayFrame(visible);int screenHeight=decor.getRootView().getHeight();int keypadHeight=screenHeight-visible.bottom;boolean keyboardVisible=keypadHeight>screenHeight*0.15;
      if(keyboardVisible==keyboardWasVisible[0])return;keyboardWasVisible[0]=keyboardVisible;
      verify.setVisibility(keyboardVisible?View.GONE:View.VISIBLE);more.setVisibility(keyboardVisible?View.GONE:View.VISIBLE);
      if(noticeHolder[0]!=null)noticeHolder[0].setVisibility(keyboardVisible?View.GONE:View.VISIBLE);
      if(keyboardVisible)scroll.post(()->scroll.fullScroll(View.FOCUS_DOWN));
    };
    decor.getViewTreeObserver().addOnGlobalLayoutListener(keyboardListener);
  }
  TextView badge(int count){TextView t=new TextView(this);t.setText(count>99?"99+":String.valueOf(count));t.setTextColor(Color.WHITE);t.setTextSize(11);t.setTypeface(null,Typeface.BOLD);t.setGravity(android.view.Gravity.CENTER);t.setBackground(circleBg(accent,26));return t;}
  void addContactRow(Button contact,int unread,String initial,int avatarColor){LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);row.setGravity(android.view.Gravity.CENTER_VERTICAL);row.setPadding(0,dp(2),0,dp(2));
    LinearLayout.LayoutParams avatarParams=new LinearLayout.LayoutParams(dp(40),dp(40));avatarParams.setMargins(dp(6),0,dp(8),0);row.addView(circle(initial,avatarColor,40,15),avatarParams);
    row.addView(contact,new LinearLayout.LayoutParams(0,-2,1));
    if(unread>0){LinearLayout.LayoutParams badgeParams=new LinearLayout.LayoutParams(dp(26),dp(26));badgeParams.setMargins(dp(8),0,dp(6),0);row.addView(badge(unread),badgeParams);}
    body.addView(row,new LinearLayout.LayoutParams(-1,-2));}
  void render(){PeerEngine e=MessengerService.engine;if(e==null){status.setText(MessengerService.problem.isEmpty()?"Offline · Tap Refresh to go online":MessengerService.problem);return;}
    if(pendingOpen!=null){String target=pendingOpen;pendingOpen=null;showChat(target);return;}
    if(selected!=null)try{e.markRead(selected);}catch(Exception ignored){}
    List<PeerEngine.Peer> people=e.peers();Collections.sort(people,(a,b)->a.online()==b.online()?a.name.compareToIgnoreCase(b.name):(a.online()?-1:1));int online=0;for(PeerEngine.Peer p:people)if(p.online())online++;status.setText(online+" online · "+e.pending()+" queued · "+e.name);
    if(selected==null){StringBuilder signature=new StringBuilder();for(PeerEngine.Group g:e.groups())signature.append(g.id).append(g.name).append(e.unread(g.id));for(PeerEngine.Peer p:people)signature.append(p.id).append(p.name).append(p.online()).append(p.security()).append(e.unread(p.id));if(signature.toString().equals(lastSignature)&&body.getChildCount()>0)return;lastSignature=signature.toString();body.removeAllViews();
      if(people.isEmpty()&&e.groups().isEmpty())body.addView(label("No contacts yet.\n\nOpen LAN Messenger on another phone or computer connected to the same Wi-Fi. No host computer is needed.\n\nIf your router blocks discovery, use Add by IP.",17));
      for(PeerEngine.Group g:e.groups()){Button contact=button(g.name+"\nGroup · "+g.members.length+" members");contact.setGravity(android.view.Gravity.LEFT|android.view.Gravity.CENTER_VERTICAL);contact.setPadding(dp(14),dp(10),dp(14),dp(10));contact.setBackgroundTintList(android.content.res.ColorStateList.valueOf(Color.rgb(245,243,250)));addContactRow(contact,e.unread(g.id),"G",Color.rgb(156,124,224));contact.setOnClickListener(v->showChat(g.id));}
      for(PeerEngine.Peer p:people){Button contact=button(p.name+"  ·  "+(p.online()?"Online":"Offline")+"\n"+p.id.substring(0,8)+" · "+p.security());contact.setGravity(android.view.Gravity.LEFT|android.view.Gravity.CENTER_VERTICAL);contact.setPadding(dp(14),dp(10),dp(14),dp(10));String initial=p.name.isEmpty()?"?":p.name.substring(0,1).toUpperCase(Locale.ROOT);addContactRow(contact,e.unread(p.id),initial,nameColor(p.id));contact.setOnClickListener(v->showChat(p.id));}return;
    }
    PeerEngine.Peer peer=null;for(PeerEngine.Peer p:people)if(p.id.equals(selected))peer=p;PeerEngine.Group group=null;for(PeerEngine.Group g:e.groups())if(g.id.equals(selected))group=g;if(peer==null&&group==null)return;verifyButton.setEnabled(peer!=null);heading.setText(group!=null?group.name+" · "+group.members.length+" members":peer.name+" · "+(peer.online()?"Online":"Offline")+" · "+peer.security());send.setEnabled(group!=null||peer.trusted());List<PeerEngine.Message> messages=e.messages(selected);
    StringBuilder signature=new StringBuilder(selected);for(PeerEngine.Message m:messages)signature.append(m.id).append(m.status);if(signature.toString().equals(lastSignature))return;lastSignature=signature.toString();boolean bottom=feed.getHeight()-scroll.getScrollY()-scroll.getHeight()<dp(120);releaseImages(feed);feed.removeAllViews();
    if(messages.isEmpty())feed.addView(label("Verify this device before chatting.\n\nQueued messages send after both verified devices reconnect. Delivered means saved on the other device.",17));
    int maxBubble=Math.min(dp(320),(int)(getResources().getDisplayMetrics().widthPixels*0.78));
    for(PeerEngine.Message m:messages){boolean mine=m.from.equals(e.id);LinearLayout card=column();card.setPadding(dp(12),dp(6),dp(12),dp(8));card.setBackground(bg(mine?bubbleMine:Color.WHITE));TextView who=label(mine?"You":e.displayName(m.from),14);who.setTypeface(null,Typeface.BOLD);who.setTextColor(mine?accent:nameColor(m.from));card.addView(who);if(m.fileName.isEmpty()){TextView text=label(m.text,17);text.setMaxWidth(maxBubble);text.setTextDirection(View.TEXT_DIRECTION_FIRST_STRONG);text.setTextIsSelectable(true);card.addView(text);}else{Bitmap thumbnail=inlineBitmap(e,m);if(thumbnail!=null){ImageView image=new ImageView(this);image.setImageBitmap(thumbnail);image.setScaleType(ImageView.ScaleType.CENTER_CROP);image.setAdjustViewBounds(false);int height=Math.max(dp(150),Math.min(dp(320),(int)((long)maxBubble*thumbnail.getHeight()/Math.max(1,thumbnail.getWidth()))));image.setLayoutParams(new LinearLayout.LayoutParams(maxBubble,height));image.setBackground(bg(Color.rgb(232,236,243)));image.setClipToOutline(true);image.setContentDescription("Open "+m.fileName);image.setOnClickListener(v->previewImage(m));card.addView(image);}TextView name=label(m.fileName+"  ·  "+String.format(Locale.ROOT,"%.1f KB",m.fileSize/1024.0),15);name.setMaxWidth(maxBubble);name.setTextIsSelectable(true);card.addView(name);LinearLayout fileActions=new LinearLayout(this);Button save=button("Save");fileActions.addView(save);save.setOnClickListener(v->exportFile(m));if(thumbnail!=null){Button open=button("Open");fileActions.addView(open);open.setOnClickListener(v->previewImage(m));}card.addView(fileActions);if(!m.text.isEmpty()){TextView caption=label(m.text,17);caption.setMaxWidth(maxBubble);caption.setTextDirection(View.TEXT_DIRECTION_FIRST_STRONG);caption.setTextIsSelectable(true);card.addView(caption);}}String when=android.text.format.DateFormat.format("MMM d, HH:mm",m.time).toString();if(mine){boolean seen=m.status.startsWith("Seen");String ticks=seen||m.status.startsWith("Delivered")?"✓✓":"✓";TextView statusLine=label(when+"  ·  "+ticks+" "+m.status,13);statusLine.setTextColor(seen?seenBlue:Color.rgb(112,128,144));card.addView(statusLine);}else{TextView statusLine=label(when,13);statusLine.setTextColor(Color.rgb(112,128,144));card.addView(statusLine);}
      LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);View spacer=new View(this);
      if(mine){row.addView(spacer,new LinearLayout.LayoutParams(0,0,1));row.addView(card,new LinearLayout.LayoutParams(-2,-2));}else{row.addView(card,new LinearLayout.LayoutParams(-2,-2));row.addView(spacer,new LinearLayout.LayoutParams(0,0,1));}
      LinearLayout.LayoutParams rowParams=new LinearLayout.LayoutParams(-1,-2);rowParams.setMargins(0,dp(5),0,dp(5));feed.addView(row,rowParams);}
    if(bottom)scroll.post(()->scroll.fullScroll(View.FOCUS_DOWN));
  }
  Bitmap inlineBitmap(PeerEngine engine,PeerEngine.Message message){try{return inlineBitmap(engine.readAttachment(message));}catch(Exception ignored){return null;}}
  Bitmap inlineBitmap(byte[] bytes){try{BitmapFactory.Options bounds=new BitmapFactory.Options();bounds.inJustDecodeBounds=true;BitmapFactory.decodeByteArray(bytes,0,bytes.length,bounds);if(bounds.outWidth<=0||bounds.outHeight<=0||(long)bounds.outWidth*bounds.outHeight>32000000)return null;bounds.inSampleSize=1;while(bounds.outWidth/bounds.inSampleSize>1000||bounds.outHeight/bounds.inSampleSize>800)bounds.inSampleSize*=2;bounds.inJustDecodeBounds=false;return BitmapFactory.decodeByteArray(bytes,0,bytes.length,bounds);}catch(Exception ignored){return null;}}
  void releaseImages(View view){if(view instanceof ImageView){ImageView image=(ImageView)view;if(image.getDrawable() instanceof android.graphics.drawable.BitmapDrawable){Bitmap bitmap=((android.graphics.drawable.BitmapDrawable)image.getDrawable()).getBitmap();image.setImageDrawable(null);if(bitmap!=null&&!bitmap.isRecycled())bitmap.recycle();}}else if(view instanceof android.view.ViewGroup){android.view.ViewGroup group=(android.view.ViewGroup)view;for(int i=0;i<group.getChildCount();i++)releaseImages(group.getChildAt(i));}}
  void verifyDevice(){PeerEngine e=MessengerService.engine;if(e==null||selected==null)return;PeerEngine.Peer peer=null;for(PeerEngine.Peer p:e.peers())if(p.id.equals(selected))peer=p;if(peer==null)return;final PeerEngine.Peer target=peer;
    try{final String code=e.pairingCode(target.id);StringBuilder formatted=new StringBuilder();for(int i=0;i<8;i++)formatted.append(code.substring(i*8,i*8+8)).append(i%2==0?" ":"\n");
      TextView text=label((target.keyChanged()?"KEY CHANGED. Check with this person before trusting their device again.\n\n":"Compare this entire safety code on BOTH devices in person or through a trusted channel.\n\n")+formatted+"\nOpen Verify device on the other device too. Confirm on each device only if every group matches.",16);text.setPadding(dp(20),dp(10),dp(20),dp(10));text.setTextIsSelectable(true);
      AlertDialog.Builder builder=new AlertDialog.Builder(this).setTitle("Verify device").setView(text).setNegativeButton("Cancel",null);
      if(!target.keyChanged())builder.setPositiveButton("Codes match — verify",(d,w)->{try{e.verify(target.id,code);render();}catch(Exception error){Toast.makeText(this,error.getMessage(),Toast.LENGTH_LONG).show();}});
      if(!target.verified.isEmpty())builder.setNeutralButton("Revoke",(d,w)->new AlertDialog.Builder(this).setTitle("Revoke verification?").setMessage("Messages stay queued until you compare and verify this device again.").setPositiveButton("Revoke",(d2,w2)->{try{e.revoke(target.id);render();}catch(Exception error){Toast.makeText(this,error.getMessage(),Toast.LENGTH_LONG).show();}}).setNegativeButton("Cancel",null).show());builder.show();
    }catch(Exception error){Toast.makeText(this,error.getMessage(),Toast.LENGTH_LONG).show();}
  }

  void chatMenu(View anchor){if(selected==null)return;PopupMenu menu=new PopupMenu(this,anchor);menu.getMenu().add("Clear conversation");menu.getMenu().add("Group members");menu.setOnMenuItemClickListener(item->{if(item.getTitle().equals("Clear conversation"))clearChat();else showMembers();return true;});menu.show();}
  void clearChat(){final PeerEngine e=MessengerService.engine;final String target=selected;if(e==null||target==null)return;new AlertDialog.Builder(this).setTitle("Clear conversation?").setMessage("Remove messages and attachments from this device and cancel pending sends. Other devices keep their copies.").setNegativeButton("Cancel",null).setPositiveButton("Clear",(d,w)->{try{e.clearConversation(target);drafts.remove(target);if(composer!=null)composer.setText("");clearPendingAttachment();lastSignature="";render();}catch(Exception error){problem(error);}}).show();}
  void showMembers(){PeerEngine e=MessengerService.engine;if(e==null)return;for(PeerEngine.Group g:e.groups())if(g.id.equals(selected)){StringBuilder text=new StringBuilder();for(String id:g.members){boolean verified=false;for(PeerEngine.Peer person:e.peers())if(person.id.equals(id))verified=person.trusted();text.append(e.displayName(id)).append(id.equals(e.id)?" (you)":verified?" · Verified":" · Verify in People").append('\n');}text.append("\nEach pair must verify each other in People. Membership is fixed for this group.");new AlertDialog.Builder(this).setTitle(g.name+" · Members").setMessage(text).setPositiveButton("OK",null).show();return;}Toast.makeText(this,"This is a direct conversation.",Toast.LENGTH_SHORT).show();}
  void createGroup(){final PeerEngine e=MessengerService.engine;if(e==null)return;final ArrayList<PeerEngine.Peer> peers=new ArrayList<>();for(PeerEngine.Peer p:e.peers())if(p.trusted())peers.add(p);if(peers.size()<2){Toast.makeText(this,"Verify at least two contacts first.",Toast.LENGTH_LONG).show();return;}
    final EditText name=input("Group name",50);final boolean[] checked=new boolean[peers.size()];String[] names=new String[peers.size()];for(int i=0;i<names.length;i++)names[i]=peers.get(i).name+" · "+peers.get(i).id.substring(0,6);
    AlertDialog dialog=new AlertDialog.Builder(this).setTitle("New group · select 2–15 contacts").setView(name).setMultiChoiceItems(names,checked,(d,which,on)->checked[which]=on).setNegativeButton("Cancel",null).setPositiveButton("Create",null).create();dialog.setOnShowListener(v->dialog.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(button->{try{ArrayList<String> ids=new ArrayList<>();for(int i=0;i<checked.length;i++)if(checked[i])ids.add(peers.get(i).id);String id=e.createGroup(name.getText().toString(),ids);dialog.dismiss();showChat(id);}catch(Exception error){problem(error);}}));dialog.show();
  }
  void pickFile(boolean photo){PeerEngine e=MessengerService.engine;if(e==null||selected==null)return;if(send!=null&&!send.isEnabled()){Toast.makeText(this,"Verify this contact first.",Toast.LENGTH_LONG).show();return;}attachmentTarget=selected;Intent intent=new Intent(Intent.ACTION_OPEN_DOCUMENT).addCategory(Intent.CATEGORY_OPENABLE).setType(photo?"image/*":"*/*");try{startActivityForResult(intent,photo?41:42);}catch(Exception error){problem(error);}}
  void capturePhoto(){if(selected==null||send==null||!send.isEnabled()){Toast.makeText(this,"Verify this contact first.",Toast.LENGTH_LONG).show();return;}try{attachmentTarget=selected;cameraFile=new File(getCacheDir(),"camera-"+UUID.randomUUID()+".jpg");cameraUri=Uri.parse("content://"+getPackageName()+".camera/capture/"+cameraFile.getName());Intent intent=new Intent(MediaStore.ACTION_IMAGE_CAPTURE).putExtra(MediaStore.EXTRA_OUTPUT,cameraUri).addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION);intent.setClipData(android.content.ClipData.newRawUri("Camera photo",cameraUri));startActivityForResult(intent,44);}catch(Exception error){if(cameraFile!=null)cameraFile.delete();problem(error);}}
  void exportFile(PeerEngine.Message message){exportMessage=message;try{startActivityForResult(new Intent(Intent.ACTION_CREATE_DOCUMENT).addCategory(Intent.CATEGORY_OPENABLE).setType("application/octet-stream").putExtra(Intent.EXTRA_TITLE,message.fileName),43);}catch(Exception error){problem(error);}}
  void problem(Exception error){Toast.makeText(this,error.getMessage()==null?"Operation failed":error.getMessage(),Toast.LENGTH_LONG).show();}
  @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(result!=RESULT_OK){if(request==44&&cameraFile!=null)cameraFile.delete();return;}final Uri uri=data==null?null:data.getData();final PeerEngine e=MessengerService.engine;if(e==null){Toast.makeText(this,"Go online and try again.",Toast.LENGTH_LONG).show();return;}
    final String target=attachmentTarget;final PeerEngine.Message exporting=exportMessage;final File captured=cameraFile;
    new Thread(()->{try{
      if(request==43&&exporting!=null&&uri!=null){byte[] bytes=e.readAttachment(exporting);try(OutputStream out=getContentResolver().openOutputStream(uri,"w")){if(out==null)throw new IOException("Cannot open destination");out.write(bytes);}ui.post(()->Toast.makeText(this,"File saved",Toast.LENGTH_SHORT).show());}
      else if((request==41||request==42)&&target!=null&&uri!=null){String name="attachment";try(Cursor cursor=getContentResolver().query(uri,new String[]{OpenableColumns.DISPLAY_NAME},null,null,null)){if(cursor!=null&&cursor.moveToFirst())name=cursor.getString(0);}if(name==null)name="attachment";try(InputStream in=getContentResolver().openInputStream(uri)){if(in==null)throw new IOException("Cannot open attachment");prepareAttachment(target,name,readLimited(in));}}
      else if(request==44&&target!=null&&captured!=null){try(InputStream in=new FileInputStream(captured)){String name=new java.text.SimpleDateFormat("yyyyMMdd-HHmmss",Locale.ROOT).format(new Date());prepareAttachment(target,"Photo-"+name+".jpg",readLimited(in));}finally{captured.delete();}}
      else if(request==45&&uri!=null){byte[] raw;try(InputStream in=getContentResolver().openInputStream(uri)){if(in==null)throw new IOException("Cannot open image");raw=readLimited(in);}Bitmap bitmap=inlineBitmap(raw);if(bitmap==null)throw new IOException("This file is not a supported image.");ByteArrayOutputStream png=new ByteArrayOutputStream();bitmap.compress(Bitmap.CompressFormat.PNG,90,png);e.setAvatar(png.toByteArray());bitmap.recycle();ui.post(()->{Toast.makeText(this,"Profile picture updated",Toast.LENGTH_SHORT).show();if(selected==null)showPeople();});}
    }catch(Exception error){if(captured!=null&&request==44)captured.delete();ui.post(()->problem(error));}},"lan-attachment").start();
  }
  byte[] readLimited(InputStream in)throws IOException{try(ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[] buffer=new byte[65536];int n;while((n=in.read(buffer))!=-1){if(out.size()+n>PeerEngine.MAX_FILE_SIZE)throw new IOException("Files must be "+(PeerEngine.MAX_FILE_SIZE/1024/1024)+" MB or smaller.");out.write(buffer,0,n);}return out.toByteArray();}}
  void prepareAttachment(String target,String name,byte[] bytes){ui.post(()->{if(!target.equals(selected))return;pendingAttachment=bytes;pendingAttachmentName=PeerEngine.safeFileName(name);pendingAttachmentTarget=target;renderPendingAttachment();if(composer!=null)composer.requestFocus();Toast.makeText(this,"Ready to send",Toast.LENGTH_SHORT).show();});}
  void renderPendingAttachment(){if(attachmentDraft==null)return;releaseImages(attachmentDraft);attachmentDraft.removeAllViews();if(pendingAttachment==null)return;attachmentDraft.setPadding(dp(10),dp(6),dp(10),dp(6));attachmentDraft.setBackground(bg(Color.rgb(235,240,250)));Bitmap bitmap=inlineBitmap(pendingAttachment);if(bitmap!=null){ImageView image=new ImageView(this);image.setImageBitmap(bitmap);image.setScaleType(ImageView.ScaleType.CENTER_CROP);image.setLayoutParams(new LinearLayout.LayoutParams(-1,dp(170)));image.setBackground(bg(Color.rgb(220,226,237)));image.setClipToOutline(true);image.setContentDescription("Preview "+pendingAttachmentName);image.setOnClickListener(v->previewBytes(pendingAttachment,pendingAttachmentName));attachmentDraft.addView(image);}attachmentDraft.addView(label(pendingAttachmentName+"  ·  "+String.format(Locale.ROOT,"%.1f KB",pendingAttachment.length/1024.0)+"\nReady to send",14));Button remove=button("Remove");remove.setOnClickListener(v->clearPendingAttachment());attachmentDraft.addView(remove);}
  void clearPendingAttachment(){pendingAttachment=null;pendingAttachmentName="";pendingAttachmentTarget=null;if(attachmentDraft!=null){releaseImages(attachmentDraft);attachmentDraft.removeAllViews();}}
  void previewImage(PeerEngine.Message message){PeerEngine e=MessengerService.engine;if(e==null)return;new Thread(()->{try{byte[] bytes=e.readAttachment(message);BitmapFactory.Options options=new BitmapFactory.Options();options.inJustDecodeBounds=true;BitmapFactory.decodeByteArray(bytes,0,bytes.length,options);if(options.outWidth<=0||options.outHeight<=0)throw new IOException("Not a supported image. Use Save file.");options.inSampleSize=1;while(options.outWidth/options.inSampleSize>1600||options.outHeight/options.inSampleSize>1600)options.inSampleSize*=2;options.inJustDecodeBounds=false;final Bitmap bitmap=BitmapFactory.decodeByteArray(bytes,0,bytes.length,options);if(bitmap==null)throw new IOException("Cannot preview image");ui.post(()->{if(isFinishing()||isDestroyed()){bitmap.recycle();return;}ImageView image=new ImageView(this);image.setImageBitmap(bitmap);image.setAdjustViewBounds(true);image.setMaxHeight(dp(500));AlertDialog dialog=new AlertDialog.Builder(this).setTitle(message.fileName).setView(image).setPositiveButton("Close",null).create();dialog.setOnDismissListener(d->{image.setImageDrawable(null);bitmap.recycle();});dialog.show();});}catch(Exception error){ui.post(()->problem(error));}},"lan-image-preview").start();}
  void previewBytes(byte[] bytes,String name){new Thread(()->{try{BitmapFactory.Options options=new BitmapFactory.Options();options.inJustDecodeBounds=true;BitmapFactory.decodeByteArray(bytes,0,bytes.length,options);if(options.outWidth<=0||options.outHeight<=0)throw new IOException("This file is not a supported image.");options.inSampleSize=1;while(options.outWidth/options.inSampleSize>1600||options.outHeight/options.inSampleSize>1600)options.inSampleSize*=2;options.inJustDecodeBounds=false;final Bitmap bitmap=BitmapFactory.decodeByteArray(bytes,0,bytes.length,options);if(bitmap==null)throw new IOException("Cannot preview image");ui.post(()->{ImageView image=new ImageView(this);image.setImageBitmap(bitmap);image.setAdjustViewBounds(true);image.setMaxHeight(dp(500));AlertDialog dialog=new AlertDialog.Builder(this).setTitle(name).setView(image).setPositiveButton("Close",null).create();dialog.setOnDismissListener(d->{image.setImageDrawable(null);bitmap.recycle();});dialog.show();});}catch(Exception error){ui.post(()->problem(error));}},"lan-draft-preview").start();}
  @Override protected void onNewIntent(Intent intent){super.onNewIntent(intent);setIntent(intent);pendingOpen=intent.getStringExtra("conversation");render();}

  static final String APP_VERSION="0.7.1";
  void showAbout(){new AlertDialog.Builder(this).setTitle("About LAN Messenger").setMessage("LAN Messenger\nVersion "+APP_VERSION+"\n\nPrivate Windows and Android messaging on a local network. No central server, host laptop, account or Internet relay.").setPositiveButton("Close",null).show();}
  void changeAvatar(){PeerEngine e=MessengerService.engine;if(e==null){Toast.makeText(this,"Go online first.",Toast.LENGTH_SHORT).show();return;}try{startActivityForResult(new Intent(Intent.ACTION_OPEN_DOCUMENT).addCategory(Intent.CATEGORY_OPENABLE).setType("image/*"),45);}catch(Exception error){problem(error);}}
  void profile(){PeerEngine e=MessengerService.engine;if(e==null){startConnection();return;}EditText name=input("Display name",30);name.setText(e.name);new AlertDialog.Builder(this).setTitle("Your profile").setMessage("Device ID: "+e.id.substring(0,8)+"\nYour contacts recognize this device even if its IP changes.").setView(name).setPositiveButton("Save",(d,w)->{try{e.rename(name.getText().toString());render();}catch(Exception error){Toast.makeText(this,"Could not save your name.",Toast.LENGTH_LONG).show();}}).setNeutralButton("Go offline",(d,w)->{stopService(new Intent(this,MessengerService.class));}).setNegativeButton("Cancel",null).show();}
  void addAddress(){PeerEngine e=MessengerService.engine;if(e==null){startConnection();return;}EditText address=input("192.168.1.20",60);address.setInputType(android.text.InputType.TYPE_CLASS_TEXT|android.text.InputType.TYPE_TEXT_VARIATION_URI);StringBuilder ips=new StringBuilder();try{Enumeration<NetworkInterface> all=NetworkInterface.getNetworkInterfaces();while(all.hasMoreElements()){Enumeration<InetAddress> addresses=all.nextElement().getInetAddresses();while(addresses.hasMoreElements()){InetAddress a=addresses.nextElement();if(a instanceof Inet4Address&&!a.isLoopbackAddress())ips.append(a.getHostAddress()).append("  ");}}}catch(Exception ignored){}
    new AlertDialog.Builder(this).setTitle("Add a device").setMessage("Your IP: "+ips+"\nEnter the other device's IP. It must be running LAN Messenger.").setView(address).setPositiveButton("Find device",(d,w)->{String value=address.getText().toString();new Thread(()->{try{e.addAddress(value);ui.post(()->{lastSignature="";render();});}catch(Exception error){ui.post(()->Toast.makeText(this,"Device not reachable. Check Wi-Fi, IP and firewall.",Toast.LENGTH_LONG).show());}}).start();}).setNegativeButton("Cancel",null).show();
  }
  @Override public void onBackPressed(){if(selected!=null)showPeople();else super.onBackPressed();}
  @Override protected void onResume(){super.onResume();active=true;ui.removeCallbacks(tick);ui.post(tick);}
  @Override protected void onPause(){super.onPause();active=false;ui.removeCallbacks(tick);saveDraft();}
  @Override protected void onDestroy(){super.onDestroy();ui.removeCallbacksAndMessages(null);}
}
